# Generated by Django 3.2.4 on 2021-06-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='videofile',
        ),
    ]
