# Generated by Django 3.2.4 on 2021-06-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_file_post_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='videofile',
            field=models.FileField(default='#', null=True, upload_to='videos/', verbose_name='video'),
        ),
    ]
