# Generated by Django 3.2.4 on 2021-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(choices=[('false', 'False'), ('true', 'True')], default=False),
        ),
    ]
